apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
    description: LAN timemachine
  creationTimestamp: null
  generation: 1
  labels:
    k8s-app: timemachine
    location: lan
  name: timemachine
  selfLink: /apis/extensions/v1beta1/namespaces/lan/deployments/timemachine
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: timemachine
      location: lan
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        description: LAN timemachine
      creationTimestamp: null
      labels:
        k8s-app: timemachine
        location: lan
      name: timemachine
    spec:
      containers:
      - env:
        - name: tz
          value: "Europe/Berlin"
        - name: SET_PERMISSIONS
          value: "false"
        - name: PASSWORD
          value: "JoooTimeMachine123"
        - name: SHARE_NAME
          value: "TimeMachine"
        - name: VOLUME_SIZE_LIMIT
          value: "0"
        - name: MIMIC_MODEL
          value: "TimeCapsule6,106"
        - name: LOG_LEVEL
          value: "info"
        - name: CUSTOM_AFP_CONF
          value: "false"
        image: marvinmarvin/docker-k8s-timemachine
        imagePullPolicy: Always
        name: timemachine
        ports:
        - containerPort: 548
          name: timemachine
          protocol: TCP
        volumeMounts:
        - mountPath: /var/netatalk
          name: k8s-cfg-timemachine
        - mountPath: /opt/timemachine
          name: pvc-timemachine
        resources: {}
        securityContext:
          privileged: true
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      volumes:
      - name: k8s-cfg-timemachine
        hostPath:
          path: /root/k8s-cfg/timemachine
          type: Directory
      - name: pvc-timemachine
        persistentVolumeClaim:
          claimName: timemachine
#      - name: k8s-cfg-timemachine-usr2
#        hostPath:
#          path: /usr2
#          type: Directory
      dnsPolicy: ClusterFirst
      hostNetwork: false
      nodeSelector:
        nodetype: nuc
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: lan-loadbalancer
    metallb.universe.tf/allow-shared-ip: lan-loadbalancer
  labels:
    k8s-app: timemachine
  name: timemachine-100
  namespace: lan
spec:
  externalTrafficPolicy: Cluster
  loadBalancerIP: 192.168.1.100
  ports:
  - name: timemachine
    port: 548
    protocol: TCP
    targetPort: timemachine
  selector:
    k8s-app: timemachine
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: lan-loadbalancer
    metallb.universe.tf/allow-shared-ip: lan-loadbalancer
  labels:
    k8s-app: timemachine
  name: timemachine-250
  namespace: lan
spec:
  externalTrafficPolicy: Cluster
  loadBalancerIP: 192.168.1.250
  ports:
  - name: timemachine
    port: 548
    protocol: TCP
    targetPort: timemachine
  selector:
    k8s-app: timemachine
  sessionAffinity: None
  type: LoadBalancer
